---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - 'docker'
      - 'firefox'
      - 'google-chrome'
      - 'iterm2'
      - 'lastpass'
      - 'macvim'
      - '1password'
      - 'cisco-spark'
      - 'spectacle'
      - 'slack'
      - 'tunnelblick'
      - 'vagrant'
      - 'vagrant-manager'
      - 'virtualbox'
      - 'virtualbox-extension-pack'
      - 'visual-studio-code'
      - 'openshift-cli'
      - 'socat'
      - 'minishift'
      - 'google-cloud-sdk'
    brew_packages:
      - 'coreutils'
      - 'connect'
      - 'autoconf'
      - 'bash-completion'
      - 'boot2docker'
      - 'docker-compose'
      - 'docker-machine'
      - 'git'
      - 'git-lfs'
      - 'jq'
      - 'fzf'
      - 'grc'
      - 'go'
      - 'nmap'
      - 'openssl'
      - 'packer'
      - 'pyenv'
      - 'python'
      - 'ssh-copy-id'
      - 'terraform'
      - 'terraform-inventory'
      - 'terraform-provisioner-ansible'
      - 'tmux'
      - 'tree'
      - 'vault'
      - 'wget'
      - 'ack'
      - 'zsh'
      - 'zsh-syntax-highlighting'
      - 'docker-machine-driver-xhyve'
      - 'watch'
      - 'packer'
    install_homebrew_if_missing: true
    python_modules:
      - 'configparser'
      - 'pylint'
      - 'virtualenv'
    upgrade_homebrew_packages: true

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: "/usr/local/bin/brew"
      register: "homebrew_check"

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: "Homebrew is missing...Install from http://brew.sh/"
      when: >
            not homebrew_check.stat.exists and
            not install_homebrew_if_missing

    - name: Installing Homebrew
      command: '/usr/bin/ruby -e "$(curl -fssl https://raw.githubusercontent.com/homebrew/install/master/install)"'
      when: >
            not homebrew_check.stat.exists and
            install_homebrew_if_missing

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ item }}"
        state: "present"
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      with_items: '{{ brew_packages }}'
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
      with_items: '{{ brew_cask_packages }}'
      when: homebrew_check.stat.exists

    - name: Installing Python Modules
      pip:
        name: "{{ item }}"
        state: "present"
      with_items: '{{ python_modules }}'

